language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "12"

env:
  - MONGOOSE_VERSION=5

install:
  - npm install
  - npm install mongoose@$MONGOOSE_VERSION

notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
